name: Schedule Planning Center Scrape

on:
  schedule:
    - cron: '0 9 * * 4'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Copy broadcast_schedule.csv to root directory
      run: cp broadcast_schedule.csv $GITHUB_WORKSPACE

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install beautifulsoup4
        pip install pandas
    - name: Run script
      run: python planningcenterscrape.py


