name: Schedule Planning Center Scrape

on:
  schedule:
    - cron: '0 9 * * 4'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install beautifulsoup4
        pip install pandas
    - name: Run script
      run: python planningcenterscrape.py
